import Head from 'next/head'
import { NextSeo } from 'next-seo'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NextSeo title="Store Builder" description="Store Builder" />

      <main>{children}</main>
    </>
  )
}
